language: python
python:
  # - 2.7
  - 3.6
  - 3.7


before_install:
  - sudo apt-get install tidy

install:
  - pip install -U setuptools
  - test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install -e .

script:
  - inv install
  - inv prep test
