# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from django.utils.translation import gettext_lazy as _

help_texts = {
    'lino_care.lib.care.migrate.Migrator' : _("""The standard migrator for care."""),
    'lino_care.lib.care.migrate.Migrator.migrate_from_1_0_1' : _("""Move Deployment and Milestone from 'tickets' to new plugin
'deploy'."""),
    'lino_care.lib.care.user_types.SiteAdmin' : _("""Can do everything."""),
    'lino_care.lib.tickets.Plugin' : _("""Adds the lino_xl.lib.votes plugin."""),
}
